/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hirokiiyoda' at '16/07/31 21:10' with Gradle 2.14.1
 *
 * @author hirokiiyoda, @date 16/07/31 21:10
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
